import time

from Pages.universitet_page import UniversitetPage
from Pages.talabalar_page import TalabalarPage
from Pages.yangiliklar_page import YangiliklarPage
from Pages.virtual_reception_page import VirtualReception
from Pages.search_function import Search
from Pages.social_media_page import SocialMediaPage

def test_inha_pages_chrome(driver_chrome):   # Chrome browser Positive Test
    driver_chrome.get('https://inha.uz/uz/asosiy/')

    universitet_page = UniversitetPage(driver_chrome)
    universitet_page.click_universitet_dropdown()
    time.sleep(2)
    universitet_page.click_iut_haqida()
    time.sleep(2)
    universitet_page.click_universitet_btn_back()
    time.sleep(2)
    universitet_page.click_rektor_haqida()
    time.sleep(2)
    universitet_page.click_universitet_btn_back()
    time.sleep(2)
    universitet_page.click_professorlar()
    time.sleep(2)
    universitet_page.click_professor_card()
    time.sleep(3)
    universitet_page.click_professor_card_exit()
    time.sleep(2)

    talabalar_page = TalabalarPage(driver_chrome)
    for i in range(2):
        talabalar_page.click_talabalar()
        time.sleep(1)
    talabalar_page.click_talabalar_assotsiatsiyasi()
    time.sleep(2)
    for i in range(2):
        talabalar_page.click_talabalar()
        time.sleep(1)
    talabalar_page.click_kutubxona()
    time.sleep(2)
    talabalar_page.click_go_to_photos()
    time.sleep(2)
    talabalar_page.click_kutubxona_photos()
    time.sleep(2)
    for i in range(5):
        talabalar_page.click_btn_right()
        time.sleep(2)
    talabalar_page.click_kutubxona_photos_exit()
    time.sleep(2)
    for i in range(2):
        talabalar_page.click_talabalar()
        time.sleep(1)
    talabalar_page.click_oquv_jadvali()
    time.sleep(2)
    talabalar_page.click_academic_calendar_pdf()
    time.sleep(3)
    talabalar_page.click_btn_back()
    time.sleep(2)

    yangiliklar_page = YangiliklarPage(driver_chrome)
    yangiliklar_page.click_yangiliklar()
    time.sleep(2)
    yangiliklar_page.click_yangiliklar_card()
    time.sleep(2)
    yangiliklar_page.click_img()
    time.sleep(2)
    for i in range(4):
        yangiliklar_page.click_img_btn_right()
        time.sleep(2)
    yangiliklar_page.click_img_btn_exit()
    time.sleep(2)

    virtual_reception = VirtualReception(driver_chrome)
    virtual_reception.click_reception_page()
    time.sleep(1)
    virtual_reception.input_full_name("Test")
    time.sleep(1)
    virtual_reception.input_region("Test")
    time.sleep(1)
    virtual_reception.input_city("Test")
    time.sleep(1)
    virtual_reception.input_address("Test")
    time.sleep(1)
    virtual_reception.input_age("22")
    time.sleep(1)
    virtual_reception.input_email("test@test.com")
    time.sleep(1)
    virtual_reception.input_phone_number("+998912345678")
    time.sleep(1)
    virtual_reception.input_text("Test")
    time.sleep(1)
    virtual_reception.click_btn_submit()
    time.sleep(2)
    virtual_reception.click_submitted_msg()
    time.sleep(2)
    for i in range(2):
        virtual_reception.click_btn_language()
        time.sleep(2)
    virtual_reception.click_uz_language()
    time.sleep(2)

    search = Search(driver_chrome)
    search.click_search_logo()
    time.sleep(2)
    search.write_input_search("kutubxona")
    time.sleep(2)
    search.click_search_result()
    time.sleep(2)
    search.click_search_photo()
    time.sleep(2)
    for i in range(5):
        search.click_search_photo_btn_right()
        time.sleep(2)
    search.click_search_photo_btn_exit()
    time.sleep(2)
    search.click_btn_main_menu()
    time.sleep(2)

    social_media = SocialMediaPage(driver_chrome)
    social_media.click_logo_instagram()
    time.sleep(3)
    social_media.click_btn_back()
    time.sleep(3)
    social_media.click_logo_telegram()
    time.sleep(3)
    social_media.click_btn_back()
    time.sleep(3)
    social_media.click_logo_facebook()
    time.sleep(3)
    social_media.click_btn_back()
    social_media.click_logo_youtube()
    time.sleep(3)
    social_media.click_btn_back()
    time.sleep(3)
    social_media.click_logo_linkedin()
    time.sleep(3)
    social_media.click_btn_back()
    time.sleep(3)
